#:schema node_modules/wrangler/config-schema.json
name = "sutando-cf"
main = "src/index.ts"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "etf"
database_id = "743b7634-c6f4-4378-b9fd-e2e3ed2b0907"
