#:schema node_modules/wrangler/config-schema.json
name = "sutando-cf"
main = "src/index.ts"
compatibility_date = "2024-08-29"
node_compat = true
compatibility_flags = ["experimental:nodejs_compat_v2"]

[[d1_databases]]
binding = "DB"
database_name = "sutando"
database_id = "34a1f123-5f7f-41d3-a8b8-5561b29df848"
