#:schema node_modules/wrangler/config-schema.json
name = "sutando-cf"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]

[[d1_databases]]
binding = "DB"
database_name = "etf"
database_id = "743b7634-c6f4-4378-b9fd-e2e3ed2b0907"
